name: "MS SQL Server 2025"
version: "1.0.0"
slug: "mssqlserver"
description: "Microsoft SQL Server 2025 database engine for Home Assistant"
url: "https://github.com/phdindota/MSSQLSERVER-HA-ADDON"
startup: services
boot: auto
arch:
  - amd64
init: false
timeout: 300
ports:
  1433/tcp: 1433
ports_description:
  1433/tcp: "SQL Server TDS port"
map:
  - "share:rw"
host_network: false
ingress: false
panel_icon: "mdi:database"
options:
  accept_eula: false
  sa_password: ""
  mssql_pid: "Developer"
  mssql_data_dir: "/share/mssqlserver/data"
  mssql_log_dir: "/share/mssqlserver/log"
  mssql_backup_dir: "/share/mssqlserver/backup"
schema:
  accept_eula: bool
  sa_password: str
  mssql_pid: "list(Developer|Express|Standard|Enterprise)"
  mssql_data_dir: str
  mssql_log_dir: str
  mssql_backup_dir: str
